train_datalist_path: 
valid_datalist_path: 
phn2id_path: 
ckpt: 

n_mels: 80
n_fft: 1024
sample_rate: 22050
hop_size: 256
win_size: 1024
f_min: 0
f_max: 8000


n_enc_channels: 128
filter_channels: 512
filter_channels_dp: 256
n_enc_layers: 6
enc_kernel: 3
enc_dropout: 0.1
n_heads: 2
window_size: 4

dec_dim: 64
beta_min: 0.05
beta_max: 20.0
pe_scale: 1000

log_dir: 
max_step: 1700000
batch_size: 16
learning_rate: 0.0001
out_size: 2

random_seed: 37